apiVersion: internal.gateway.networking.k8s.io/v1alpha1
kind: GEPDetails
number: 2645
name: UDPRoute
status: Alpha
authors:
  - zac-nixon
references:
  - https://www.ietf.org/rfc/rfc768.txt
featureNames:
  - UDPRoute